### ISSUE TITLE
documentation sample is slightly wrong

### ISSUE THREAD

**Issue by rednaxus** [flyingunicorn222/1broker-client#1]
Under basic:

should not be account.overview, but user.overview

**Comment by flyingunicorn222** [comment]
@rednaxus thanks a lot for the heads up!

Would you like to contribute with a better documentation or even writing some tests?

If you execute ````make docs```` some docs will be generated but needs a lot of polishing.

Another area needing help would be to write some tests using a test library ( like mocha ) and mocking 1Broker API with something like sinon.js so tests would be able to happen without hitting the official api ( and spend coins ).
