### ISSUE TITLE
Does this library overwrite my referral_id with yours ?

### ISSUE THREAD

**Issue by gauraviitr** [flyingunicorn222/1broker-client#2]
Hi,

First of all, amazing work on the library.
I notice you mention that by default the referral_id while placing orders will be yours (as can be seen in the config file). 
If I place an order using order.create while specifiying my referral_id as one of the params, will it still use your referral id and ignore the value I provided ?

Thanks !

**Comment by flyingunicorn222** [comment]
First of all apologies for not replying this earlier and thanks for your complement.

If you [look at the source code](https://github.com/flyingunicorn222/1broker-client/blob/v2/src/client.coffee#L5) you will see you can set a referral_id when creating your instance of the client although i would appreciate if you can keep mine as a way of donating to the library, i'll always be updating and improving this as their API changes and soon will be providing a library for 1Fox as well, so if you would like to support my work please keep the original referral_id !
